version: "1.0"
info:
  model: int-scaffold
packages:
- name: Emea02user_IsraelDemo2Project
  gitServerName: michalit0
  gitUrl: https://github.com/michalit0/Emea02user_IsraelDemo2Project
  gitUsername: michalit0
  gitBranch: main
