version: "1.0"
info:
  model: int-scaffold
packages:
- name: Emea02user_IsraelDemo2Project
  gitServerName: michalit0
  gitUrl: https://github.com/michalit0/Emea02user_IsraelDemo2Project
  gitUsername: michalit0
  gitBranch: main
- name: emea02user_israelPJ
  gitServerName: michalit0
  gitUrl: https://github.com/michalit0
  gitUsername: michalit0
  gitBranch: master
- name: ParsingUtilsPck
  gitServerName: michalit0
  gitUrl: https://github.com/AvivSimDS
  gitUsername: michalit0
  gitBranch: master
- name: ParseNames
  gitServerName: emea02user_avivsimds_public_github
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: master
services:
- serviceName: project.emea02user_israeldemo2.integrations:Wrap2Packages
  packages:
  - name: Emea02user_IsraelDemo2Project
    version: "1.0"
  - name: emea02user_israelPJ
    version: "1.0"
  - name: ParsingUtilsPck
    version: "1.0"
  - name: ParseNames
    version: "1.0"
- serviceName: IsraelDemoPackage.integrations:GetVersion
  packages:
  - name: emea02user_israelPJ
    version: "1.0"
- serviceName: ParsingUtilsPackage.integrations:TripleTokenize
  packages:
  - name: ParsingUtilsPck
    version: "1.0"
- serviceName: parseNames:tokenize_name
  packages:
  - name: ParseNames
    version: "1.0"
- serviceName: project.emea02user_israeldemo2.integrations:ShipmentHandler
  packages:
  - name: Emea02user_IsraelDemo2Project
    version: "1.0"
  - name: ParseNames
    version: "1.0"
  - name: emea02user_israelPJ
    version: "1.0"
  - name: ParsingUtilsPck
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.emea02user_israeldemo2.integrations:ComplexDocTypeHandler
  packages:
  - name: Emea02user_IsraelDemo2Project
    version: "1.0"
  - name: ParseNames
    version: "1.0"
  - name: emea02user_israelPJ
    version: "1.0"
  - name: ParsingUtilsPck
    version: "1.0"
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
